name: Python application

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with pyinstaller
        run: pyinstaller pomodoro.spec
      - name: Upload binary to release
        uses: sventaro/upload-release-action@v2
        with:
          assets:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: dist/pomodoro
            tag: ${{ github.ref }}
            file_glob: true
